In [1]:
import pickle

In [19]:
#file = 'history.obj'
file = 'pi.obj'

In [20]:
history = pickle.load(open(file, 'rb'))

In [21]:
history

3.141592653589793

In [22]:
import numpy as np

In [23]:
0*np.nan

nan

In [24]:
np.nan == np.nan

False

In [25]:
np.inf > np.nan

False

In [26]:
np.nan - np.nan

nan

In [27]:
0.3 == 3*0.1

False

In [28]:
0.3 == (3*0.1)

False

In [37]:
7*0.1

0.7000000000000001

In [30]:
1*0.1

0.1

In [39]:
0.1 + 0.2+0.4

0.7000000000000001

In [40]:
1 + .3

1.3

In [41]:
Z = np.diag(1+np.arange(4), k = -1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [46]:
Z = np.zeros((15,15), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

In [48]:
np.unravel_index(101,(6,7,8))

(1, 5, 5)

In [50]:
for i in range(100):
    #print(i, np.unravel_index(i,(6,7,8)))

SyntaxError: unexpected EOF while parsing (<ipython-input-50-8ad28a9ee7fa>, line 2)

In [52]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

10
10


In [53]:
range(5)

range(0, 5)

In [54]:
[range(5), -1]

[range(0, 5), -1]

In [56]:
for i in range(0,5):
    print(i)

0
1
2
3
4
